// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sl.proto

package slproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SLObject struct {
	SessionId            int32    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Crc32                int32    `protobuf:"varint,2,opt,name=crc32,proto3" json:"crc32,omitempty"`
	ReqCrc32             int32    `protobuf:"varint,3,opt,name=reqCrc32,proto3" json:"reqCrc32,omitempty"`
	Object               []byte   `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SLObject) Reset()         { *m = SLObject{} }
func (m *SLObject) String() string { return proto.CompactTextString(m) }
func (*SLObject) ProtoMessage()    {}
func (*SLObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0dcac48c9b29803, []int{0}
}

func (m *SLObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SLObject.Unmarshal(m, b)
}
func (m *SLObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SLObject.Marshal(b, m, deterministic)
}
func (m *SLObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SLObject.Merge(m, src)
}
func (m *SLObject) XXX_Size() int {
	return xxx_messageInfo_SLObject.Size(m)
}
func (m *SLObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SLObject.DiscardUnknown(m)
}

var xxx_messageInfo_SLObject proto.InternalMessageInfo

func (m *SLObject) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SLObject) GetCrc32() int32 {
	if m != nil {
		return m.Crc32
	}
	return 0
}

func (m *SLObject) GetReqCrc32() int32 {
	if m != nil {
		return m.ReqCrc32
	}
	return 0
}

func (m *SLObject) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

type MatchResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Map                  string   `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	CurUserId            int32    `protobuf:"varint,4,opt,name=curUserId,proto3" json:"curUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchResult) Reset()         { *m = MatchResult{} }
func (m *MatchResult) String() string { return proto.CompactTextString(m) }
func (*MatchResult) ProtoMessage()    {}
func (*MatchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0dcac48c9b29803, []int{1}
}

func (m *MatchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchResult.Unmarshal(m, b)
}
func (m *MatchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchResult.Marshal(b, m, deterministic)
}
func (m *MatchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchResult.Merge(m, src)
}
func (m *MatchResult) XXX_Size() int {
	return xxx_messageInfo_MatchResult.Size(m)
}
func (m *MatchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchResult.DiscardUnknown(m)
}

var xxx_messageInfo_MatchResult proto.InternalMessageInfo

func (m *MatchResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MatchResult) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MatchResult) GetMap() string {
	if m != nil {
		return m.Map
	}
	return ""
}

func (m *MatchResult) GetCurUserId() int32 {
	if m != nil {
		return m.CurUserId
	}
	return 0
}

type Bool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0dcac48c9b29803, []int{2}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0dcac48c9b29803, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type DollResult struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	CurPos               int32    `protobuf:"varint,2,opt,name=curPos,proto3" json:"curPos,omitempty"`
	CurPlayer            int32    `protobuf:"varint,3,opt,name=curPlayer,proto3" json:"curPlayer,omitempty"`
	NextPlayer           int32    `protobuf:"varint,4,opt,name=nextPlayer,proto3" json:"nextPlayer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DollResult) Reset()         { *m = DollResult{} }
func (m *DollResult) String() string { return proto.CompactTextString(m) }
func (*DollResult) ProtoMessage()    {}
func (*DollResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0dcac48c9b29803, []int{4}
}

func (m *DollResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DollResult.Unmarshal(m, b)
}
func (m *DollResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DollResult.Marshal(b, m, deterministic)
}
func (m *DollResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DollResult.Merge(m, src)
}
func (m *DollResult) XXX_Size() int {
	return xxx_messageInfo_DollResult.Size(m)
}
func (m *DollResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DollResult.DiscardUnknown(m)
}

var xxx_messageInfo_DollResult proto.InternalMessageInfo

func (m *DollResult) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *DollResult) GetCurPos() int32 {
	if m != nil {
		return m.CurPos
	}
	return 0
}

func (m *DollResult) GetCurPlayer() int32 {
	if m != nil {
		return m.CurPlayer
	}
	return 0
}

func (m *DollResult) GetNextPlayer() int32 {
	if m != nil {
		return m.NextPlayer
	}
	return 0
}

type SignIn struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignIn) Reset()         { *m = SignIn{} }
func (m *SignIn) String() string { return proto.CompactTextString(m) }
func (*SignIn) ProtoMessage()    {}
func (*SignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0dcac48c9b29803, []int{5}
}

func (m *SignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignIn.Unmarshal(m, b)
}
func (m *SignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignIn.Marshal(b, m, deterministic)
}
func (m *SignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignIn.Merge(m, src)
}
func (m *SignIn) XXX_Size() int {
	return xxx_messageInfo_SignIn.Size(m)
}
func (m *SignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SignIn.DiscardUnknown(m)
}

var xxx_messageInfo_SignIn proto.InternalMessageInfo

func (m *SignIn) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Match struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0dcac48c9b29803, []int{6}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Doll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Doll) Reset()         { *m = Doll{} }
func (m *Doll) String() string { return proto.CompactTextString(m) }
func (*Doll) ProtoMessage()    {}
func (*Doll) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0dcac48c9b29803, []int{7}
}

func (m *Doll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Doll.Unmarshal(m, b)
}
func (m *Doll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Doll.Marshal(b, m, deterministic)
}
func (m *Doll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Doll.Merge(m, src)
}
func (m *Doll) XXX_Size() int {
	return xxx_messageInfo_Doll.Size(m)
}
func (m *Doll) XXX_DiscardUnknown() {
	xxx_messageInfo_Doll.DiscardUnknown(m)
}

var xxx_messageInfo_Doll proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SLObject)(nil), "slproto.SLObject")
	proto.RegisterType((*MatchResult)(nil), "slproto.MatchResult")
	proto.RegisterType((*Bool)(nil), "slproto.Bool")
	proto.RegisterType((*User)(nil), "slproto.User")
	proto.RegisterType((*DollResult)(nil), "slproto.DollResult")
	proto.RegisterType((*SignIn)(nil), "slproto.SignIn")
	proto.RegisterType((*Match)(nil), "slproto.Match")
	proto.RegisterType((*Doll)(nil), "slproto.Doll")
}

func init() {
	proto.RegisterFile("sl.proto", fileDescriptor_a0dcac48c9b29803)
}

var fileDescriptor_a0dcac48c9b29803 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0xcb, 0x4e, 0x02, 0x31,
	0x14, 0xcd, 0x74, 0x1e, 0x0e, 0x17, 0x35, 0xa4, 0x31, 0x66, 0x24, 0xc4, 0x90, 0xea, 0x82, 0x15,
	0x0b, 0xf8, 0x03, 0x74, 0x01, 0x89, 0x46, 0x52, 0xe2, 0x07, 0x0c, 0xa5, 0xd1, 0x31, 0xa5, 0xc5,
	0x3e, 0x8c, 0xfe, 0xbd, 0x69, 0xa7, 0x82, 0x84, 0xdd, 0x3d, 0xf7, 0xdc, 0xdc, 0xf3, 0x80, 0xd2,
	0x88, 0xf1, 0x4e, 0x2b, 0xab, 0xf0, 0x99, 0x11, 0x61, 0x20, 0x1a, 0xca, 0xd5, 0xd3, 0xcb, 0xfa,
	0x83, 0x33, 0x8b, 0x07, 0xd0, 0x31, 0xdc, 0x98, 0x46, 0xc9, 0xc5, 0xa6, 0x4a, 0x86, 0xc9, 0x28,
	0xa7, 0x87, 0x05, 0xbe, 0x82, 0x9c, 0x69, 0x36, 0x9d, 0x54, 0x28, 0x30, 0x2d, 0xc0, 0x7d, 0x28,
	0x35, 0xff, 0x7c, 0x08, 0x44, 0x1a, 0x88, 0x3d, 0xc6, 0xd7, 0x50, 0xa8, 0xf0, 0xb9, 0xca, 0x86,
	0xc9, 0xe8, 0x9c, 0x46, 0x44, 0x34, 0x74, 0x9f, 0x6b, 0xcb, 0xde, 0x29, 0x37, 0x4e, 0x58, 0x7c,
	0x09, 0xa8, 0xf9, 0xd3, 0x43, 0xcd, 0x06, 0xdf, 0x41, 0xee, 0x0c, 0xd7, 0xa6, 0x42, 0xc3, 0x74,
	0xd4, 0x9d, 0x5c, 0x8c, 0xa3, 0xd7, 0xf1, 0xab, 0xe1, 0x9a, 0xb6, 0x1c, 0xee, 0x41, 0xba, 0xad,
	0x77, 0x41, 0xb2, 0x43, 0xfd, 0xe8, 0xdd, 0x33, 0xa7, 0xfd, 0xcd, 0x62, 0x13, 0x04, 0x73, 0x7a,
	0x58, 0x90, 0x01, 0x64, 0x33, 0xa5, 0x84, 0x4f, 0xf1, 0x55, 0x0b, 0xc7, 0x83, 0x5e, 0x49, 0x5b,
	0x40, 0xe6, 0x90, 0xf9, 0xbb, 0x13, 0x2b, 0x7d, 0x28, 0xbd, 0x9c, 0xac, 0xb7, 0x3c, 0xc4, 0xee,
	0xd0, 0x3d, 0xf6, 0x9f, 0x0c, 0x53, 0x9a, 0xc7, 0xd8, 0x2d, 0x20, 0x16, 0xe0, 0x51, 0x09, 0x11,
	0xa3, 0xf5, 0x20, 0x95, 0x6e, 0x1b, 0x1f, 0xfa, 0xd1, 0x77, 0xc2, 0x9c, 0x5e, 0x2a, 0x13, 0x6b,
	0x8c, 0x28, 0xba, 0x5f, 0x8a, 0xfa, 0x87, 0xeb, 0xf8, 0xf1, 0xb0, 0xc0, 0xb7, 0x00, 0x92, 0x7f,
	0xdb, 0x48, 0xb7, 0xe1, 0xfe, 0x6d, 0xc8, 0x3d, 0x14, 0xab, 0xe6, 0x4d, 0x2e, 0xe4, 0x91, 0xe3,
	0xe4, 0xd8, 0x31, 0xb9, 0x81, 0x3c, 0xf4, 0x7e, 0x6a, 0x8b, 0x14, 0x90, 0x79, 0xdb, 0x33, 0x34,
	0x47, 0xeb, 0x22, 0xb4, 0x3d, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x52, 0xb8, 0x23, 0x2e,
	0x02, 0x00, 0x00,
}
